baseURL: https://edfloreshz.github.io/blog/
languageCode: en-us
paginate: 5
relativeURLs: true
title: edfloreshz

theme: "PaperMod"

params:
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hello!
    subtitle: "My name is Eddy, I write about Rust 🦀"
    imageUrl: resources/_gen/images/profile.jpg
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile
    buttons:
      - name: Articles
        url: articles
      - name: Search
        url: search
      - name: Tags
        url: tags

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
    - name: twitter
      url: "https://twitter.com/edfloreshz"
    - name: telegram
      url: "https://t.me/edfloreshz"
    - name: github
      url: "https://github.com/edfloreshz"
  outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary
